### ASSIGNMENT - 8

### TOPIC : NLP

### MODEL : AMAZON REVIEW

# 

In [1]:
import pandas as pd

import numpy as np

from sklearn.metrics import confusion_matrix , accuracy_score

from sklearn.tree import DecisionTreeClassifier

DT = DecisionTreeClassifier ( )

from sklearn.naive_bayes import MultinomialNB

NB = MultinomialNB ( )

from sklearn.model_selection import train_test_split

pd.set_option ( "display.max_columns" , None )

from nltk.corpus import stopwords

import string

from sklearn.feature_extraction.text import CountVectorizer 

In [2]:
Amazon = pd.read_csv ( r"F:\PANDAS DATA\AmazonFoodReviews.csv" , encoding = 'utf8')

Amazon

Id   ProductId          UserId                      ProfileName  \
0            1  B001E4KFG0  A3SGXH7AUHU8GW                       delmartian   
1            2  B00813GRG4  A1D87F6ZCVE5NK                           dll pa   
2            3  B000LQOCH0   ABXLMWJIXXAIN  Natalia Corres "Natalia Corres"   
3            4  B000UA0QIQ  A395BORC6FGVXV                             Karl   
4            5  B006K2ZZ7K  A1UQRSCLF8GW1T    Michael D. Bigham "M. Wassir"   
...        ...         ...             ...                              ...   
568449  568450  B001EO7N10  A28KG5XORO54AY                 Lettie D. Carter   
568450  568451  B003S1WTCU  A3I8AFVPEE8KI5                        R. Sawyer   
568451  568452  B004I613EE  A121AA1GQV751Z                    pksd "pk_007"   
568452  568453  B004I613EE   A3IBEVCTXKNOH          Kathy A. Welch "katwel"   
568453  568454  B001LR2CU2  A3LGQPJCZVL9UC                         srfell17   

        HelpfulnessNumerator  HelpfulnessDenominator  Score        Time  \
0                          1                       1      5  1303862400   
1                          0                       0      1  1346976000   
2                          1                       1      4  1219017600   
3                          3                       3      2  1307923200   
4                          0                       0      5  1350777600   
...                      ...                     ...    ...         ...   
568449                     0                       0      5  1299628800   
568450                     0                       0      2  1331251200   
568451                     2                       2      5  1329782400   
568452                     1                       1      5  1331596800   
568453                     0                       0      5  1338422400   

                                   Summary  \
0                    Good Quality Dog Food   
1                        Not as Advertised   
2                    "Delight" says it all   
3                           Cough Medicine   
4                              Great taffy   
...                                    ...   
568449                 Will not do without   
568450                        disappointed   
568451            Perfect for our maltipoo   
568452  Favorite Training and reward treat   
568453                         Great Honey   

                                                     Text  
0       I have bought several of the Vitality canned d...  
1       Product arrived labeled as Jumbo Salted Peanut...  
2       This is a confection that has been around a fe...  
3       If you are looking for the secret ingredient i...  
4       Great taffy at a great price.  There was a wid...  
...                                                   ...  
568449  Great for sesame chicken..this is a good if no...  
568450  I'm disappointed with the flavor. The chocolat...  
568451  These stars are small, so you can give 10-15 o...  
568452  These are the BEST treats for training and rew...  
568453  I am very satisfied ,product is as advertised,...  

[568454 rows x 10 columns]

### DATA CLEANING

In [3]:
Amazon.isnull ( ).sum ( ) [ Amazon.isnull ( ).sum ( ) > 0 ]

ProfileName    16
Summary        27
dtype: int64

In [4]:
Amazon = Amazon.loc [ : , [ 'Score' , 'Text' ] ]

Amazon.isnull ( ).sum ( ) [ Amazon.isnull ( ).sum ( ) > 0 ]

Series([], dtype: int64)

In [5]:
Amazon.Text = Amazon.Text.str.lower ( )

### STOP WORDS AND PUNCTUATION

In [6]:
Stop_Words = stopwords.words ( 'english' )

def text_process ( message ) :
    
    nopunc = [ i for i in message if i not in string.punctuation ]
    nopunc = ''.join ( nopunc )
    
    return [ i for i in nopunc.split ( ) if i not in Stop_Words ]

Amazon['Text'].apply ( text_process )

0         [bought, several, vitality, canned, dog, food,...
1         [product, arrived, labeled, jumbo, salted, pea...
2         [confection, around, centuries, light, pillowy...
3         [looking, secret, ingredient, robitussin, beli...
4         [great, taffy, great, price, wide, assortment,...
                                ...                        
568449    [great, sesame, chickenthis, good, better, res...
568450    [im, disappointed, flavor, chocolate, notes, e...
568451    [stars, small, give, 1015, one, training, sess...
568452    [best, treats, training, rewarding, dog, good,...
568453    [satisfied, product, advertised, use, cereal, ...
Name: Text, Length: 568454, dtype: object

### COUNT VECTORIZATION

In [7]:
Text_Count = CountVectorizer ( analyzer = text_process ).fit ( Amazon['Text'])

Amazon_X = Text_Count.transform( Amazon['Text'] )

In [8]:
X_Train , X_Test , Y_Train , Y_Test = train_test_split ( Amazon_X , Amazon['Score'] , test_size = 0.2 ) 

print ( "Shapes" )

print ( "X_Train" , X_Train.shape)

print ( "Y_Train" , Y_Train.shape)

print ( "X_Test" , X_Test.shape)

print ( "Y_Test" , Y_Test.shape)

Shapes
X_Train (454763, 240626)
Y_Train (454763,)
X_Test (113691, 240626)
Y_Test (113691,)


### DT MODEL

In [9]:
DT.fit ( X_Train , Y_Train )

Predicted = DT.predict ( X_Test )

Confusion = confusion_matrix ( Y_Test , Predicted )

Confusion

array([[ 6485,   560,   569,   596,  2312],
       [  796,  2663,   507,   461,  1460],
       [  709,   432,  4193,   906,  2300],
       [  579,   372,   789,  8350,  6020],
       [ 1675,   911,  1605,  4252, 64189]], dtype=int64)

In [10]:
accuracy_score ( Y_Test , Predicted  ) * 100

75.53808129051552

### NAIVE BAYES

In [11]:
NB.fit ( X_Train , Y_Train )

Predict = NB.predict ( X_Test )

Confusion_NB = confusion_matrix ( Y_Test , Predict )

Confusion_NB

array([[ 6729,   338,   552,   544,  2359],
       [ 1333,   872,   742,   925,  2015],
       [ 1004,   136,  2060,  2067,  3273],
       [  636,    89,   521,  5915,  8949],
       [ 1467,   192,   550,  4362, 66061]], dtype=int64)

In [12]:
accuracy_score ( Y_Test , Predict) * 100

71.8060356580556

## CONVERTING THE MATRIX 

In [13]:
Amazon = pd.read_csv ( r"F:\PANDAS DATA\AmazonFoodReviews.csv" , encoding = 'utf8')

Amazon.Score.replace ( { 2 : 1 , 3 : 2 , 4 : 3 , 5 : 3 } , inplace = True )


### STOP WORDS AND PUNCTUATION

In [14]:
Stop_Words = stopwords.words ( 'english' )

def text_process ( message ) :
    
    nopunc = [ i for i in message if i not in string.punctuation ]
    nopunc = ''.join ( nopunc )
    
    return [ i for i in nopunc.split ( ) if i not in Stop_Words ]

Amazon['Text'].apply ( text_process )

0         [I, bought, several, Vitality, canned, dog, fo...
1         [Product, arrived, labeled, Jumbo, Salted, Pea...
2         [This, confection, around, centuries, It, ligh...
3         [If, looking, secret, ingredient, Robitussin, ...
4         [Great, taffy, great, price, There, wide, asso...
                                ...                        
568449    [Great, sesame, chickenthis, good, better, res...
568450    [Im, disappointed, flavor, The, chocolate, not...
568451    [These, stars, small, give, 1015, one, trainin...
568452    [These, BEST, treats, training, rewarding, dog...
568453    [I, satisfied, product, advertised, I, use, ce...
Name: Text, Length: 568454, dtype: object

### COUNT VECTORIZATION

In [15]:
Text_Count = CountVectorizer ( analyzer = text_process ).fit ( Amazon['Text'])

Amazon_X = Text_Count.transform( Amazon['Text'] )

In [16]:
X_Train , X_Test , Y_Train , Y_Test = train_test_split ( Amazon_X , Amazon['Score'] , test_size = 0.2 ) 

print ( "Shapes" )

print ( "X_Train" , X_Train.shape)

print ( "Y_Train" , Y_Train.shape)

print ( "X_Test" , X_Test.shape)

print ( "Y_Test" , Y_Test.shape)

Shapes
X_Train (454763, 291795)
Y_Train (454763,)
X_Test (113691, 291795)
Y_Test (113691,)


### DT MODEL

In [17]:
DT.fit ( X_Train , Y_Train )

Predicted = DT.predict ( X_Test )

Confusion = confusion_matrix ( Y_Test , Predicted )

Confusion

array([[10873,   849,  4857],
       [ 1137,  4084,  3379],
       [ 3687,  2175, 82650]], dtype=int64)

In [18]:
accuracy_score ( Y_Test , Predicted  ) * 100

85.85288193436595

### NAIVE BAYES

In [19]:
NB.fit ( X_Train , Y_Train )

Predict = NB.predict ( X_Test )

Confusion_NB = confusion_matrix ( Y_Test , Predict )

Confusion_NB

array([[10750,  1025,  4804],
       [ 1654,  2226,  4720],
       [ 3350,  1981, 83181]], dtype=int64)

In [20]:
accuracy_score ( Y_Test , Predict) * 100

84.57749514033652